"""001_initial_enterprise_schema

Revision ID: 84a8909d7f3d
Revises: 
Create Date: 2026-09-01 11:00:54.223112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '84a8909d7f3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('dedup_hash', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('mitre_technique_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_alerts_dedup_hash'), 'alerts', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_alerts_host'), 'alerts', ['host'], unique=False)
    op.create_index(op.f('ix_alerts_indicator'), 'alerts', ['indicator'], unique=False)
    op.create_index(op.f('ix_alerts_source_ip'), 'alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_alerts_username'), 'alerts', ['username'], unique=False)
    op.add_column('assets', sa.Column('asset_type', sa.Enum('SERVER', 'WORKSTATION', 'FIREWALL', 'ROUTER', 'DATABASE', 'CLOUD_RESOURCE', name='assettype'), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.drop_column('audit_logs', 'metadata')
    op.add_column('case_evidence', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('case_evidence', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('case_evidence', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('case_evidence', sa.Column('sha256_hash', sa.String(), nullable=False))
    op.add_column('case_evidence', sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
    op.alter_column('case_evidence', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_case_evidence_sha256_hash'), 'case_evidence', ['sha256_hash'], unique=False)
    op.create_foreign_key(None, 'case_evidence', 'users', ['uploaded_by_id'], ['id'])
    op.drop_column('case_evidence', 'file_path')
    op.drop_column('case_evidence', 'evidence_type')
    op.drop_column('case_evidence', 'metadata')
    op.add_column('cases', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.alter_column('cases', 'case_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('OPEN', 'INVESTIGATING', 'PENDING', 'RESOLVED', 'CLOSED', name='casestatus'),
               existing_nullable=True)
    op.create_foreign_key(None, 'cases', 'users', ['created_by_id'], ['id'])
    op.add_column('execution_logs', sa.Column('step_id', sa.Integer(), nullable=True))
    op.add_column('execution_logs', sa.Column('action', sa.String(), nullable=True))
    op.add_column('execution_logs', sa.Column('duration_ms', sa.Float(), nullable=True))
    op.add_column('execution_logs', sa.Column('input_data', sa.JSON(), nullable=True))
    op.add_column('execution_logs', sa.Column('output_data', sa.JSON(), nullable=True))
    op.add_column('execution_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('execution_logs', 'execution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('execution_logs', 'metadata')
    op.drop_column('execution_logs', 'message')
    op.add_column('incident_events', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('incident_events', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.alter_column('incident_events', 'incident_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'incident_events', type_='foreignkey')
    op.create_foreign_key(None, 'incident_events', 'users', ['created_by_id'], ['id'])
    op.drop_column('incident_events', 'user_id')
    op.drop_column('incident_events', 'metadata')
    op.add_column('incidents', sa.Column('mitre_technique_id', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('mitre_tactic', sa.String(), nullable=True))
    op.add_column('incidents', sa.Column('case_id', sa.Integer(), nullable=True))
    op.add_column('incidents', sa.Column('contained_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'incidents', 'cases', ['case_id'], ['id'])
    op.add_column('indicators', sa.Column('is_simulation', sa.Boolean(), nullable=True))
    op.add_column('indicators', sa.Column('raw_data', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_indicators_indicator_type'), 'indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_indicators_reputation'), 'indicators', ['reputation'], unique=False)
    op.drop_column('indicators', 'created_at')
    op.drop_column('indicators', 'updated_at')
    op.drop_column('indicators', 'metadata')
    op.add_column('playbook_executions', sa.Column('playbook_version', sa.String(), nullable=True))
    op.add_column('playbook_executions', sa.Column('duration_ms', sa.Float(), nullable=True))
    op.alter_column('playbook_executions', 'playbook_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('playbook_steps', sa.Column('name', sa.String(), nullable=False))
    op.add_column('playbook_steps', sa.Column('requires_approval', sa.Boolean(), nullable=True))
    op.add_column('playbook_steps', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.alter_column('playbook_steps', 'playbook_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('playbooks', sa.Column('trigger_type', sa.String(), nullable=True))
    op.add_column('playbooks', sa.Column('version', sa.String(), nullable=True))
    op.create_index(op.f('ix_playbooks_name'), 'playbooks', ['name'], unique=True)
    op.drop_column('playbooks', 'trigger')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playbooks', sa.Column('trigger', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_playbooks_name'), table_name='playbooks')
    op.drop_column('playbooks', 'version')
    op.drop_column('playbooks', 'trigger_type')
    op.alter_column('playbook_steps', 'playbook_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('playbook_steps', 'retry_count')
    op.drop_column('playbook_steps', 'requires_approval')
    op.drop_column('playbook_steps', 'name')
    op.alter_column('playbook_executions', 'playbook_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('playbook_executions', 'duration_ms')
    op.drop_column('playbook_executions', 'playbook_version')
    op.add_column('indicators', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.add_column('indicators', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('indicators', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_index(op.f('ix_indicators_reputation'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_indicator_type'), table_name='indicators')
    op.drop_column('indicators', 'raw_data')
    op.drop_column('indicators', 'is_simulation')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'contained_at')
    op.drop_column('incidents', 'case_id')
    op.drop_column('incidents', 'mitre_tactic')
    op.drop_column('incidents', 'mitre_technique_id')
    op.add_column('incident_events', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.add_column('incident_events', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'incident_events', type_='foreignkey')
    op.create_foreign_key(None, 'incident_events', 'users', ['user_id'], ['id'])
    op.alter_column('incident_events', 'incident_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('incident_events', 'created_by_id')
    op.drop_column('incident_events', 'details')
    op.add_column('execution_logs', sa.Column('message', sa.TEXT(), nullable=True))
    op.add_column('execution_logs', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.alter_column('execution_logs', 'execution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('execution_logs', 'error_message')
    op.drop_column('execution_logs', 'output_data')
    op.drop_column('execution_logs', 'input_data')
    op.drop_column('execution_logs', 'duration_ms')
    op.drop_column('execution_logs', 'action')
    op.drop_column('execution_logs', 'step_id')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.alter_column('cases', 'status',
               existing_type=sa.Enum('OPEN', 'INVESTIGATING', 'PENDING', 'RESOLVED', 'CLOSED', name='casestatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('cases', 'case_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cases', 'created_by_id')
    op.add_column('case_evidence', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.add_column('case_evidence', sa.Column('evidence_type', sa.VARCHAR(), nullable=False))
    op.add_column('case_evidence', sa.Column('file_path', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'case_evidence', type_='foreignkey')
    op.drop_index(op.f('ix_case_evidence_sha256_hash'), table_name='case_evidence')
    op.alter_column('case_evidence', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('case_evidence', 'uploaded_by_id')
    op.drop_column('case_evidence', 'sha256_hash')
    op.drop_column('case_evidence', 'file_size_bytes')
    op.drop_column('case_evidence', 'file_type')
    op.drop_column('case_evidence', 'filename')
    op.add_column('audit_logs', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('assets', 'asset_type')
    op.drop_index(op.f('ix_alerts_username'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_indicator'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_host'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_hash'), table_name='alerts')
    op.drop_column('alerts', 'mitre_technique_id')
    op.drop_column('alerts', 'dedup_hash')
    # ### end Alembic commands ###
